// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shsmqlvrafnkywrbgtur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoc21xbHZyYWZua3l3cmJndHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODcxNDksImV4cCI6MjA3MjQ2MzE0OX0.EK9kqVoCE7r52C4qSaNG05v4vaVtWsfC-9l6B_gr1gQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});